add scanvi
openproblems-bio/openproblems-v2 pull request #191
Opened 2023-06-21 11:40 UTC by danielStrobl

## Describe your changes

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Tests succeed and look good!

2023-06-21 17:40 UTC, rcannood commented
Please let me know when this PR is ready for review ^^

2023-07-27 12:09 UTC, danielStrobl commented
@rcannood ready for review

2023-07-27 18:49 UTC, KaiWaldrant requested changes

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +    image: ghcr.io/openproblems-bio/base_r:1.0.0
```suggestion
    image: ghcr.io/openproblems-bio/base_r:1.0.1
```

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +          - scanpy
```suggestion
```
scanpy is now included in base image

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/script.py
> +output_type = config["functionality"]["info"]["subtype"]
```suggestion
```
no longer required

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/script.py
> +adata.uns['hvg'] = par['hvg']
```suggestion
```

please remove, will be extracted from config file

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +    label: Scanvi
```suggestion
    label: ScanVI
```

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +    description : "TODO"
please add description

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/script.py
> +    config = yaml.safe_load(file)
```suggestion
```

no longer needed to read config due to removal of `output_type`

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +  - type: nextflow
Add directives for nextflow: you can change the labels to e.g. `highmem` , `midmem` depending on the requirements of the method and how much memory or cpu it needs.

```suggestion
  - type: nextflow
    directives:
      label: [ lowmem, lowcpu ]
```

2023-07-27 18:49 UTC, KaiWaldrant commented on src/tasks/batch_integration/methods/scanvi/config.vsh.yaml
> +  - type: nextflow
It was not in the docs but will be added and in the schemas

2023-07-27 18:54 UTC, KaiWaldrant commented
Can you also update the changelog by adding the method to `### V1 MIGRATION` in the task section

2023-08-01 09:48 UTC, KaiWaldrant approved these changes

2023-08-07 10:22 UTC, merged