remove ns-list workflows
openproblems-bio/openproblems-v2 pull request #208
Opened 2023-07-20 14:38 UTC by KaiWaldrant

## Describe your changes
resolve the integration test fail. Remove the ns-list action for the workflows directory. It does not exist.

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [x] Bug fixes

- [x] Proposed changes are described in the CHANGELOG.md

- [x] CI Tests succeed and look good!

2023-07-21 04:09 UTC, rcannood approved these changes

2023-07-22 12:11 UTC, DriesSchaumont commented
@KaiWaldrant, could you make a commit which contains the partial commit message 'ci force'? This way we can check if this workflow works with the proposed changes.

2023-07-22 12:13 UTC, DriesSchaumont requested changes
Hi @KaiWaldrant, could you create an empty commit with the partial commit message 'ci force'? This way we should be able to check if the proposed changes work before moving to main.

2023-07-24 07:08 UTC, KaiWaldrant commented
the test fails are mitigated by PR #206

2023-07-24 07:34 UTC, merged