Refactor denoising
openproblems-bio/openproblems-v2 pull request #27
Opened 2022-11-22 14:59 UTC by KaiWaldrant

2022-11-23 06:13 UTC, rcannood requested changes
Making some good progress here!

I think the most important comment is to get the unit tests working, as it will be able to tell you when certain things aren't working.

2022-11-23 09:44 UTC, KaiWaldrant commented on src/denoising/data_processing/split_data/script.py
> +output_test.layers["counts"] = scipy.sparse.csr_matrix(X_test).astype(float)
I Allways get the error that the matrix size is not the same as it expected in the counts layer. that's why I delete the layer first.

2022-11-23 09:45 UTC, KaiWaldrant commented on src/denoising/control_methods/no_denoising/config.vsh.yaml
> +    code_url: "https://github.com/czbiohub/molecular-cross-validation"
was a copy paste from the v1 script. but you are correct as it is not even related.

2022-11-23 09:49 UTC, KaiWaldrant commented on src/denoising/methods/dca/script.py
> +dca(input_train, epochs=par["epochs"])
DCA still needs to be worked on as it has package issues and was not updated with the correct layers etc

2022-11-23 09:50 UTC, KaiWaldrant commented on src/denoising/methods/knn_smoothing/script.py
> +X = input_train.X.transpose().toarray()
Same here. script needs to be updated to the current way of working. Also has python package issues.

2022-11-23 11:53 UTC, rcannood commented on src/denoising/data_processing/split_data/script.py
> +output_test.layers["counts"] = scipy.sparse.csr_matrix(X_test).astype(float)
I see, fair enough!

Maybe it makes sense to make the output objects from scratch anyway, so ensure that no extra fields get passed to the methods anyways

2022-12-01 14:27 UTC, rcannood commented
@KaiWaldrant Could you list in the Changelog what this PR adds to the repository? When applicable, could you also note what the differences are?

2022-12-01 22:26 UTC, rcannood commented on src/denoising/methods/dca/script.py
> -del input_train.layers["counts"]
Oops, my bad

2022-12-02 05:56 UTC, rcannood approved these changes
LGTM, as long as you can add a changelog afterwards @KaiWaldrant

2022-12-02 05:57 UTC, merged