Add SIMLR
openproblems-bio/openproblems-v2 pull request #312
Opened 2023-12-15 09:28 UTC by sainirmayi

## Describe your changes
Add a new SIMLR method to the dimensionality reduction task.

## Issue ticket number and link
Closes #xxxx (Replace xxxx with the GitHub issue number)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Bug fixes

- [ ] Proposed changes are described in the CHANGELOG.md

- [ ] CI Tests succeed and look good!

2023-12-15 11:13 UTC, KaiWaldrant requested changes
small changes

2023-12-15 11:13 UTC, KaiWaldrant commented on src/tasks/dimensionality_reduction/methods/simlr/script.R
> +input <- anndata::read_h5ad(par[["input"]])
just for future reference in r the items in a list can also be called with `par$input`. Much easier to type.

2023-12-15 12:32 UTC, KaiWaldrant approved these changes
LGTM

2023-12-15 12:58 UTC, rcannood approved these changes
looks good to me! minor suggestions for the R script

2023-12-16 08:31 UTC, rcannood commented
Thanks @sainirmayi !

2023-12-16 08:31 UTC, merged