Create skeleton comp
openproblems-bio/openproblems-v2 pull request #78
Opened 2023-02-02 20:45 UTC by KaiWaldrant

This component creates skeleton files:

* config.vsh.yaml
* script.py/R

depending on the script language, task, and component.

2023-03-09 09:26 UTC, rcannood requested changes

2023-03-09 09:26 UTC, rcannood commented on src/common/create_skeleton/script.py
> +    ]
```suggestion
  tmpl['functionality']['info']['metrics'] = [{
      'metric_id': 'metric_id',
      'metric_name': 'Metric Name',
      'metric_description': 'metric description',
      'min': 0,
      'max': 1,
      'maximize': 'true',
    }]
```

2023-03-09 09:26 UTC, rcannood commented on src/common/create_skeleton/script.py
> +  conf['functionality']['test_resources'][0]['path'] = 'script.r'
```suggestion

  conf['functionality']['resources'][0]['type'] = 'r_script'
  conf['functionality']['resources'][0]['path'] = 'script.R'

  conf['functionality']['test_resources'][0]['type'] = 'r_script'
  conf['functionality']['test_resources'][0]['path'] = 'script.R'
```

2023-03-09 20:57 UTC, KaiWaldrant commented
I'm thinking about creating 2 skeleton components for metric and methods. I still need to add an py/Rscript template for metrics and this is going to make the script too "complicated".

What do you think @rcannood ?

2023-03-14 21:57 UTC, rcannood commented
Hmm.. I would prefer 1 component, I think. Am I right in understanding that it ATM it works as intended?

In the future, I might consider using a python script + jinja templating engine, but if it works we can leave it as is for now.

2023-03-15 08:48 UTC, KaiWaldrant commented
yes this should work as intended

2023-03-16 15:35 UTC, KaiWaldrant commented on src/common/create_skeleton/script.py
as mentioned in the file comments the output anndata still contain `adata`

2023-03-16 22:00 UTC, rcannood commented on src/common/create_skeleton/script.py
Phew.

2023-03-17 17:10 UTC, merged