Batch integration refactoring
openproblems-bio/openproblems-v2 pull request #81
Opened 2023-02-08 21:17 UTC by rcannood

2023-02-09 10:22 UTC, KaiWaldrant commented on src/batch_integration/embedding/methods/combat/script.py
change to new normalized layers

2023-02-09 10:23 UTC, KaiWaldrant commented on src/batch_integration/embedding/methods/combat/script.py
> +        'scaled': par['scaling'],
remove scaling

2023-02-09 10:24 UTC, KaiWaldrant commented on src/batch_integration/embedding/methods/combat/script.py
> +    'scaling': True
remove scaling, incorperated in normalization

2023-02-09 10:24 UTC, KaiWaldrant commented on src/batch_integration/embedding/methods/combat/script.py
> +        'scaled': par['scaling'],
remove scaling, see above

2023-02-09 10:25 UTC, KaiWaldrant commented on src/batch_integration/embedding/methods/combat/script.py
> +adata.write_h5ad(par['output'], compression='gzip')
```suggestion
input.write_h5ad(par['output'], compression='gzip')
```
change adata to input

2023-03-12 22:00 UTC, KaiWaldrant commented
@rcannood split_dataset  and a metric fail on the organism field because I think that is not in the dataset.

2023-03-17 20:43 UTC, KaiWaldrant requested changes

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/methods/bbknn/config.vsh.yaml
> +    method_name: BBKNN
change it later with an issue. still needs to be done for all tasks

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_score.yaml
> +        name: output_id
```suggestion
        name: output_type
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_graph.yaml
> +        name: output_id
```suggestion
        name: output_type
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_feature.yaml
> +        name: output_id
```suggestion
        name: output_type
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_embedding.yaml
> +        name: output_id
```suggestion
        name: output_type
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_embedding.yaml
> +        required: false
```suggestion
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_graph.yaml
> +        required: false
```suggestion
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_score.yaml
> +        required: false
```suggestion
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/methods/scanorama_feature/script.py
> +del(adata.X)
```suggestion
del adata.X
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/metrics/cell_cycle_conservation/config.vsh.yaml
> +  #     required: true
remove if not needed
```suggestion
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/metrics/clustering_overlap/script.py
> +
```suggestion
```

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/workflows/download.tsv
remove ?

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/workflows/run/config.vsh.yaml
needs to be updated after merge

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/workflows/run/main.nf
will be updated after merge

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/workflows/run/preprocessing.tsv
remove /update after merge

2023-03-17 20:43 UTC, KaiWaldrant commented on src/batch_integration/workflows/run/run_nextflow.sh
will be updated after merge

2023-03-20 08:44 UTC, KaiWaldrant requested changes

2023-03-20 08:44 UTC, KaiWaldrant commented on src/batch_integration/api/anndata_integrated_feature.yaml
> +        required: false
```suggestion
```

2023-03-21 09:43 UTC, rcannood commented on src/batch_integration/api/comp_split_dataset.yaml
> +  # test_resources:
Or add it back? Could you look into this?

2023-03-24 13:04 UTC, merged