Update/config info fields
openproblems-bio/openproblems-v2 pull request #99
Opened 2023-03-29 19:31 UTC by KaiWaldrant

update the config fields to new names.

2023-04-03 13:50 UTC, KaiWaldrant commented
@mumichae Can you check the `summary` and `descrption` fields in the config of the batch integration task?
I've just done a copy and paste from the v1

2023-04-07 10:56 UTC, rcannood requested changes
Just one small suggestion

2023-04-07 18:27 UTC, rcannood requested changes
Could you add an entry to the changelog ? :Bow:

2023-04-11 11:05 UTC, rcannood approved these changes

2023-04-11 11:06 UTC, merged